server:
  port: 8085

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  main:
    allow-circular-references: true
